apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: testwebsite
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/lcarilla/flux-test2
