apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: testwebsite
  namespace: default
spec:
  interval: 1m0s
  path: "./deployments/testwebsite/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: testwebsite
